### PR TITLE
fix: configurable watchdog timeout

### LINKED ISSUE #85: bug: watch dog timing out on goerli
### Problem
Goerli WatchTower deployment is crashing

```
2023-10-04T07:31:09.006Z ERROR chainContext:runBlockWatcher:5: Watchdog timeout

2023-10-04T07:30:40.056Z ERROR checkForAndPlaceOrder:_pollLegacy:5:2.9@9806576: Error on CALL to getTradeableOrderWithSignature. Simulate: https://dashboard.tenderly.co/gp-v2/watch-tower-prod/simulator/new?network=5&contractAddress=0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74&rawFunctionInput=0x26e0a1960000000000000000000000008654d1136f2a760ba3e1c9e131cb9ad217921b52000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000000000260000000000000000000000000910d00a310f7dc5b29fe73458f47f519be547d3d000000000000000000000000000000000000000000000000000000189e3b096000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000140000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d600000000000000000000000091056d4a53e1faa1a84306d4deaec71085394bc80000000000000000000000008654d1136f2a760ba3e1c9e131cb9ad217921b5200000000000000000000000000000000000000000000000000b1a2bc2ec500000000000000000000000000000000000000000000000000063fa67b061775f0c90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000007080000000000000000000000000000000000000000000000000000000000000000506960793899dbd9225c61c44bd44927462151c82dec95315cf937f6b95ef21f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

2023-10-04T07:30:40.056Z ERROR checkForAndPlaceOrder:_handleGetTradableOrderCall:5:2.9@9806576: checkForAndPlaceOrder:_handleGetTradableOrderCall:5:2.9@9806576 Unexpected error LowLevelError: low-level call failed     at _pollLegacy (/usr/src/app/dist/src/domain/checkForAndPlaceOrder.js:340:19)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async _processConditionalOrder (/usr/src/app/dist/src/domain/checkForAndPlaceOrder.js:141:26)     at async checkForAndPlaceOrder (/usr/src/app/dist/src/domain/checkForAndPlaceOrder.js:70:32)     at async processBlock (/usr/src/app/dist/src/domain/chainContext.js:213:20)     at async JsonRpcProvider.<anonymous> (/usr/src/app/dist/src/domain/chainContext.js:155:21) {   data: '0xf3ec7a9f' }
```

### Impact
Causing restarts as well as alerts for on call

### To reproduce
Check for logs in `goerli-watch-tower` deployment

### Expected behaviour
The service should not crash

### Screenshots/logs
Search for "Watchdog timeout" in ES
Example, https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/Uk7oi

### Tenderly watch-tower version/commit hash
- `v1.0.1-rc.0`

### PR DESCRIPTION
**Pull request by mfw78**
# Description
Some chains aren't created equal, so having a constant watch dog timeout for the block watcher isn't suitable.

# Changes

- [x] Add user-configurable watch-dog timeout for the block watcher.
- [x] Some gardening to unify around integer type assertions for CLI options (NOTE: deploymentBlock not considered for integer assertions).

## How to test

1. Attempt to run with a non-integer option value that should be an integer. Observe failure to start.
2. Start with `--watchdog-timeout` flag set to non-default value, such as 120, and observe block watcher running with a 120s timeout.

## Related Issues

Fixes #85

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

File: src/domain/chainContext.ts [hunk 1]
```diff
@@ -225,19 +225,19 @@ export class ChainContext {
...
    * 1. Check if there are any `ConditionalOrderCreated` events, and index these.
    * 2. Check if any orders want to create discrete orders.
    */
-  private async runBlockWatcher() {
+  private async runBlockWatcher(watchdogTimeout: number) {
     const { provider, registry, chainId } = this;
     const log = getLogger(`chainContext:runBlockWatcher:${chainId}`);
     // Watch for new blocks
-    log.info("👀 Start block watcher");
+    log.info(`👀 Start block watcher with ${watchdogTimeout}s timeout`);
```
Comment (anxolin) [inline src/domain/chainContext.ts:240]: ubernit: I think is not super relevant the timeout in the info message. Could be DEBUG. We don't expose any of the configs. If you find it useful, we can expose the relevant ones under DEBUG

File: src/index.ts [hunk 2]
```diff
@@ -134,6 +139,14 @@ async function main() {
   await program.parseAsync();
 }
 
+function parseIntOption(option: string, _value: string) {
+  const parsed = Number(option);
```
Comment (anxolin) [inline src/index.ts:143]: why not delegint the `_value` if we are not using? does it give you an error?

File: src/domain/chainContext.ts (hunk 1 above)
Comment (mfw78) [reply src/domain/chainContext.ts:240]: Solid standard for not emitting config as a base rule for >= INFO. Configured to emit this for `debug` level in a separate line.

File: src/index.ts (hunk 2 above)
Comment (mfw78) [reply src/index.ts:143]: Because I'm silly and always think of absolute function signatures. A curse of solidity :see_no_evil: (removed `_value` and it's not complaining).

**Review by anxolin — APPROVED** [review]
